### ISSUE TITLE
Allow to define additional columns for domain inference

### ISSUE THREAD

**Issue by johanneskoester** [koesterlab/datavzrd#102]
For tick plots and heatmaps, it would be nice to be able to specify additional columns that should be used in addition to the current column to determine the domain:

```
plot:
  ticks:
    scale: linear
    aux-domain-columns:
      - some-other-column
```
