### ISSUE TITLE
Add new render-html keyword and allow integration of aux-libraries

### ISSUE THREAD

**Issue by fxwiegand** [koesterlab/datavzrd#161]
```yaml
views:
  gene-mycn-plot:
    dataset: gene-mycn
    render-html:
      script-path: my-custom-script.js # in the script, I can access a variable data with the dataset in json format, and in the rendered view there is a div with id="canvas" which I can manipulate like I like from within the script.
aux-libraries:
  - https://cdnjs.org/d3.js
```
