### ISSUE TITLE
Allow rendering custom content into any heatmap cell

### ISSUE THREAD

**Issue by fxwiegand** [koesterlab/datavzrd#170]
```yaml
heatmap:
  scale: linear
  range:
    - white
    - blue
  # Allow to render custom content into any heatmap cell
  # (e.g. from a different column of the same row).
  custom-content: |
    function(value, row) {
      return row.someothercolumn;
    }
```
