### ISSUE TITLE
Allow setting float-precision per column

### ISSUE THREAD

**Issue by fxwiegand** [koesterlab/datavzrd#178]
```yaml
name: my_report
    datasets:
        table-a:
            path: test.tsv
    views:
        table-a:
            dataset: table-a
            page-size: 100
            render-table:
                columns:
                    some-numeric-col:
                        precision: 4 # default is 2
```
