### ISSUE TITLE
Allow labeling header rows with new keyword label

### ISSUE THREAD

**Issue by fxwiegand** [koesterlab/datavzrd#181]
```yaml
render-table:
  headers:
    1:
      label: Some header label # this should be displayed left of the header row.
      plot:
        heatmap:
          ...
```
