### ISSUE TITLE
Add new plot type bars

### ISSUE THREAD

**Issue by fxwiegand** [koesterlab/datavzrd#236]
Sometimes instead of a tick plot, a bar plot might be useful:
```yaml
plot:
  bars:
    scale: linear
```
