### ISSUE TITLE
Small row height in Firefox and Chrome

### ISSUE THREAD

**Issue by mikelove** [koesterlab/datavzrd#263]
hi, I'm just playing around today.

<img width="376" alt="Screen Shot 2022-11-11 at 2 29 20 PM" src="https://user-images.githubusercontent.com/69203/201416009-4000a741-88ce-4914-a7b6-5eec8e38173e.png">

Any idea why this would show up?

It looks correct when I "View as Plot".

```
name: My report
datasets:
  table-a:
    path: "table-a.csv"
default-view: table-a
views:
  table-a:
    dataset: table-a
    render-table:
      columns:
        x:
          plot:
            heatmap:
              scale: linear
              color-scheme: blues
        y:
          plot:
            heatmap:
              scale: linear
              color-scheme: blues
```

```
name,x,y
mike,1,2
foo,2,3
bar,3,4
zoo,4,5
jk,5,6
...
```

**Comment by fxwiegand** [comment]
Hi @mikelove,
thanks for the bug report! I think all my test cases included plots etc. that prevented the line height to be that small. I will take care of the fix shortly.

**Comment by mikelove** [comment]
Looks good on my end

<img width="284" alt="Screen Shot 2022-11-11 at 3 19 48 PM" src="https://user-images.githubusercontent.com/69203/201425201-a657a054-d06a-467c-8b25-0a6e7aa95c0f.png">

**Comment by fxwiegand** [comment]
> Looks good on my end
> 
> <img alt="Screen Shot 2022-11-11 at 3 19 48 PM" width="284" src="https://user-images.githubusercontent.com/69203/201425201-a657a054-d06a-467c-8b25-0a6e7aa95c0f.png">

Should be in final production shortly 😄
Regarding you heatmap configuration the `scheme` should be used for ordinal scales. For continuous scales you can use the `range` option:

```yaml
plot:
    heatmap:
        scale: linear
        range:
            - white
            - blue
```
